---

git_repo: https://github.com/keepplace/keepplace-backend.git

project_name: keep_place_production
application_name: Keep Place


external_host: keep.place

home_folder: /opt/instamovie
# TODO add task to create folder for the DB
database_location: /opt/instamovie/data/keep_place_production

swap_file_path: /swapfile
swap_file_size: 2G